_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.openstreetmap.org/copyright' target='_blank'>&copy; OpenStreetMap</a> <a href='https://www.openstreetmap.org/fixthemap' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 121.4976
  - 25.0632
  - 18
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
name: OSM Bright 2
source: "tmsource:///Users/onlinemad/git/osm-bright.tm2source"
styles: 
  - style.mss
  - road.mss
  - labels.mss
  - fonts.mss
template: ''
